name: tests

on:
  push:
    branches: [main]

jobs:
  common-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - run: npm test
